# -*- coding: utf-8 -*-
"""modul_penjumlahan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19JvlUnPRY1aaa_ympKVTLl1jkGidx-lO

# GitHub Note
"""

def penjumlahah(angka_1, angka_2):
  # x = float(input(angka1))
  # y = float(input(angka2))
  total = angka_1 + angka_2
  return total

angka_1 = float(input("Masukkan angka pertama: "))
angka_2 =  float(input("Masukkan angka kedua: "))
penjumlahan(angka_1,angka_2)
